app:
  title: My Company Developer Portal
  baseUrl: https://backstage-5448985382.us-central1.run.app
  packages: all
  extensions:
    - entity-card:catalog-graph/relations
    - page:catalog:
        config:
          path: /
    - page:tech-radar:
        config:
          path: /tech-radar

organization:
  name: My Company

backend:
  baseUrl: https://backstage-5448985382.us-central1.run.app
  listen:
    port: ${PORT}
    host: 0.0.0.0
  auth:
    externalAccess:
      - type: static
        options:
          token: ${BACKEND_SECRET}
          subject: legacy-default-config
    keys:
      - secret: ${BACKEND_AUTH_SECRET}
  cors:
    origin:
      - https://backstage-5448985382.us-central1.run.app
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: /cloudsql/${PROJECT_ID}:${REGION}:backstage-db
      user: backstage
      password: ${BACKSTAGE_DB_PASS}
      database: backstage
  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com

dynamicPlugins:
  rootDirectory: dynamic-plugins-root

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
      webhookSecret: ${GITHUB_WEBHOOK_SECRET}

auth:
  environment: production
  providers:
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
    okta:
      production:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_AUDIENCE}

techdocs:
  builder: external      
  generator:
    runIn: local
  publisher:
    type: googleGcs
    googleGcs:
      bucketName: ${PROJECT_ID}-techdocs

scaffolder:
  defaultAuthor:
    name: Backstage
    email: backstage@elitecorpusa.com

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User, Template]
  processingInterval: { seconds: 30 }
  refreshInterval:    { seconds: 30 }
  locations:
    - type: url
      target: target: https://raw.githubusercontent.com/udhayakiran-2609/template-structure/main/catalog-info.yaml

    - type: url
      target: https://github.com/sairam3333/backstage-catalog-sample3/blob/main/backstage-catalog-new/groups/org-groups.yaml
      rules:
        - allow: [Group, User]
    - type: url
      target: https://github.com/sairam3333/backstage-catalog-sample3/blob/main/backstage-catalog-new/groups/org-users.yaml
      rules:
        - allow: [Group, User]  

permission:
  enabled: true

  rbac:
    admin:
      users:
        - name: user:default/udhayakaran

    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission

    policies-csv-file: ./rbac/rbac-policy.csv
    conditionalPoliciesFile: ./rbac/rbac-conditions.yaml

    defaultPermissions:
      defaultRole: role:default/user

      basicPermissions:
        - permission: catalog.entity.read
          effect: allow

        - permission: catalog.location.read
          effect: allow

        - permission: scaffolder.task.read
          effect: allow
        
  