steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'backstage'
      - '--image=${_IMAGE}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--project=${PROJECT_ID}'
    entrypoint: gcloud

substitutions:
  _REGION: us-central1
  _IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/backstage/app:${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY